# Generated by Django 5.0.4 on 2024-05-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
