# Generated by Django 5.0.4 on 2024-05-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_launch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_of_product',
            field=models.ImageField(null=True, upload_to='productImg'),
        ),
    ]
