# Generated by Django 5.0.4 on 2024-05-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
