# Generated by Django 5.0.4 on 2024-05-09 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_review_product_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('particular_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitem', to=settings.AUTH_USER_MODEL)),
                ('product_of_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitem', to='products.product')),
            ],
        ),
    ]
